### PR TITLE
Renamed address search to Find address

### PR DESCRIPTION
**Pull request by MattOz-CDS**
We need to adjust the wording on the address look up submit button so that it matches that suggested by [ GDS design pattern](https://design-system.service.gov.uk/patterns/addresses/) for address input.

### CODE REVIEW

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Andy, is it acceptable to you? @andybroomfield

**Review by andybroomfield — APPROVED** [review]
Seems fine, is there a way to make this configurable?

**Comment by finnlewis** [comment]
Merge it @MattOz-CDS ! :)

**Comment by MattOz-CDS** [comment]
Thanks Finn .. :)

**Comment by Adnan-cds** [comment]
>  is there a way to make this configurable?

That sounds like a good idea.  Feel free to raise a ticket and assign it to me or Matt.

**Pull request merged**
