### PR TITLE
Address lookup webform element

### LINKED ISSUE #3: Address lookup Webform element
Turn the existing [BHCC](https://www.brighton-hove.gov.uk) address lookup element into a generic one that can be powered by a variety of address lookup APIs.  Andy Broomfield of BHCC has kindly provided us with the BHCC address lookup code which forms the basis for this task.

@andrew-wallis @andybroomfield @tom-steel @richardaclarke @willguv

### PR DESCRIPTION
**Pull request by Adnan-cds**
Turns the existing BHCC address lookup Webform element into a Geocoder plugin-based address lookup Webform element.

## Test steps
- Install the bhcc_central_hub *submodule* alongside the localgov_forms module.
- Add the *BHCC Central Hub Residential* and *BHCC Central Hub Commercial* Geocoder plugins from /admin/config/system/geocoder/geocoder-provider
- Add the *Localgov address lookup* Webform element to any Webform.  While configuring this Webform element, select either the "BHCC Central Hub Residential" or the "BHCC Central Hub Commercial" or both the Geocoder plugins.
- Try searching for Brighton-based postcodes from the Address lookup element.  Example postcodes: BN1 3AA (residential) or BN1 1JE (commercial).

## Note
- This is the **first cut** of the BHCC  address lookup element's LocalGov port.  While it works, it is not production ready.
- Apart from replacing "bhcc_" prefixes with "localgov_forms_" prefixes, this version uses Geocoder plugins for address lookup.
- The bhcc_central_hub module's presence is temporary until we have more [UPRN](https://en.wikipedia.org/wiki/Unique_Property_Reference_Number) supporting Geocoder plugins for testing.
- I have noticed some redundant code which will need purging later.

Closes #3

### CODE REVIEW

**Comment by andybroomfield** [comment]
Nice work @Adnan-cds 
I assume this is very Work in Progress, but I'll take a look to see if I can get it up and running.

**Comment by Adnan-cds** [comment]
Ready for review @tom-steel @richardaclarke

**Comment by ekes** [comment]
@Adnan-cds might be good to chat about where bits like the bcc specific code, and the address geocoder interface could end up, being specific and general items respectively. You around for Merge Monday?

**Comment by andybroomfield** [comment]
Just to add the BHCC Central Hub geocoders are considered internal so should not be part of the general release.

**Comment by andybroomfield** [comment]
Well its working.
Using a BHCC CentralHub geocoder.
Screenshot 2021-10-11 at 11 28 06 am

And using the Open Street Map geocoder, has an odd issue of address line one being rendered as the word NULL (I assume it is that address isn't there, but could do with some error handling).
Screenshot 2021-10-11 at 11 18 41 am

**Comment by andybroomfield** [comment]
Can this also work outside webforms? Its use is also powering the [Parking Zones lookup](https://www.brighton-hove.gov.uk/parking-zones).

**Comment by ekes** [comment]
> Can this also work outside webforms? Its use is also powering the [Parking Zones lookup](https://www.brighton-hove.gov.uk/parking-zones).

I'm assuming with what @Adnan-cds mention's above, and in the related issue, we can move some of this into Localgov Geo or some other module, so that generalised look-up code can be used elsewhere in the site?

Apropos I wondering if doing things like https://github.com/localgovdrupal/localgov_forms/pull/6/files#diff-d0a62bf50bb31bd179601898d6daa79758cb022e7d600d529acd66cd53de4e0dR16 and announcing the geocoder supports them might not be better done with separate Interfaces and/or Traits. Even an extended Nominatim geocoder could also use the trait for UPRN (as it _can_ return them when it knows them - just doesn't know many https://overpass-turbo.eu/s/1bWO ). But more importantly it's a way for the additional fields you @andybroomfield were mentioning could be flagged up.

**Comment by Adnan-cds** [comment]
> might be good to chat about where bits like the bcc specific code, and the address geocoder interface could end up, being specific and general items respectively. You around for Merge Monday?

Sorry Ekes, I wasn't working yesterday :( The BHCC specific code will eventually have to be removed.  The goal of this pull request is to just bring the code into the repo in a reasonable format (coding standards etc.).  It needs more work to be considered production ready.

As you said earlier, we should have a separate package for the Ordnance survey geocoder.  I managed to get a working version on Friday but it is not fully complete yet.  I am thinking of moving the LocalGov Address interface into the repo for that geocoder as part of a different (yet to be born) ticket.

> Just to add the BHCC Central Hub geocoders are considered internal so should not be part of the general release.

Fully agree Andy.  I need to create a mock geocoder for the automated test.  Once that's done and the Ordnance survey geocoder is ready, I hope to drop the bhcc_central_hub submodule.

> And using the Open Street Map geocoder, has an odd issue of address line one being rendered as the word NULL

I will check.  Thanks for spotting.  I was using the Nominatim geocoder for testing non-bhcc addressed and that one worked.  But I will check the Open Street Map geocoder now.

> we can move some of this into Localgov Geo or some other module

Interesting that you are saying this.  I was thinking on Friday of asking you if we can do this :)

**Comment by andybroomfield** [comment]
> Fully agree Andy. I need to create a mock geocoder for the automated test. Once that's done and the Ordnance survey geocoder is ready, I hope to drop the bhcc_central_hub submodule.

@Adnan-cds  Thanks for refactoring it and including a geocoder address model to get the UPRN, thats a problem I was trying crack and couldn't fiqure out.

**Comment by andybroomfield** [comment]
Are we looking at merging this and then working on the refactor as seperate issues?
Just think we should hold on a release until some of this is resolved but might be easier to tackle the issues in their own branches.

**Comment by Adnan-cds** [comment]
> Are we looking at merging this and then working on the refactor as seperate issues?

That's the current intention.  Sorry, I should have been more explicit in my initial comment above.

> Just think we should hold on a release until some of this is resolved but might be easier to tackle the issues in their own branches.

Totally agree.  This address lookup thing isn't even in alpha stage.  So a release is out of question.

**Comment by ekes** [comment]
All sounds like it's heading in the right direction to me :+1:

**Review by andybroomfield — APPROVED** [review]
I'm happy to merge this as is as its not heading to release, and then we start spillitng out the issues raised on this PR as seperate issues.

**Comment by Adnan-cds** [comment]
Thanks Andy.  I am merging this.  I have fixed the "Null" address line issue in the mean time.  I will raise that as a separate pull request once we have some more tests to reproduce that scenario.

**Pull request merged**
