### PR TITLE
Hook Update: Adds uuid to LocalGov Forms Date formats

### PR DESCRIPTION
**Pull request by MattOz-CDS**
Adds a uuid to LocalGov Form Date that do not have one. This is to address this [issue](https://github.com/localgovdrupal/localgov_forms/issues/77).

### CODE REVIEW

**Comment by finnlewis** [comment]
Looking good, makes sense, just need someone to test and review and approve.

**Comment by andybroomfield** [comment]
This works in that I see a UUID added where one is not there before.
I see the UUID added at the end instead of the start, not sure if that has any significance.
```yaml
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: gMTJgkHIlhoBdHg-gzueURSBTF3eCol5J7nq4LG9zv0
id: localgov_forms_date_datetime
label: 'LocalGOV Forms Datetime'
locked: false
pattern: 'd-m-Y\TH:i:sO'
uuid: c6e3d567-2bb7-42e2-8dc0-950d8371e591

```

**Comment by MattOz-CDS** [comment]
Thanks for your feedback @andybroomfield, It's much appreciated. I've amended it so that the uuid is now placed at the top of the config. I'd be ever so grateful if you could please take another look at it when you have time. Thanks.

**Comment by markconroy** [comment]
@andybroomfield have you time to look at this? I don't have any installation of localgov_form to test via update rather than installing.

Looks like the code is good and should be fine to approve.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Review by andybroomfield — APPROVED** [review]
Seems to be in the right place now, thanks @MattOz-CDS 
```
array(9) {                                                    
    ["uuid"]=>                                                  
    string(36) "9d0caa66-0239-4504-aede-507d7890fa3a"           
    ["langcode"]=>                                              
    string(2) "en"                                              
    ["status"]=>                                                
    bool(true)                                                  
    ["dependencies"]=>                                          
    array(0) {                                                  
    }                                                           
    ["_core"]=>                                                 
    array(1) {                                                  
      ["default_config_hash"]=>                                 
      string(43) "A5_rdbLse54yYAebcvqcw4ZZotFW-tAomYZPC8Dpvik"  
    }                                                           
    ["id"]=>                                                    
    string(30) "localgov_forms_date_short_date"                 
    ["label"]=>                                                 
    string(25) "LocalGOV Forms Short Date"                      
    ["locked"]=>                                                
    bool(false)                                                 
    ["pattern"]=>                                               
    string(5) "d-m-Y"                                           
  }                                                             
  array(9) {                                                    
    ["uuid"]=>                                                  
    string(36) "c4151871-f47d-478f-bab4-bee413f654c9"           
    ["langcode"]=>                                              
    NULL                                                        
    ["status"]=>                                                
    bool(true)                                                  
    ["dependencies"]=>                                          
    array(0) {                                                  
    }                                                           
    ["_core"]=>                                                 
    array(1) {                                                  
      ["default_config_hash"]=>                                 
      string(43) "gMTJgkHIlhoBdHg-gzueURSBTF3eCol5J7nq4LG9zv0"  
    }                                                           
    ["id"]=>                                                    
    string(28) "localgov_forms_date_datetime"                   
    ["label"]=>                                                 
    string(23) "LocalGOV Forms Datetime"                        
    ["locked"]=>                                                
    bool(false)                                                 
    ["pattern"]=>                                               
    string(13) "d-m-Y\TH:i:sO"                                  
  }                                                             
  {                                                             
      "0": {                                                    
          "localgov_forms_date": {                              
              "8003": {                                         
                  "results": {                                  
                      "query": null,                            
                      "success": true                           
                  },                                            
                  "type": "update"                              
              }                                                 
          }                                                     
      },                                                        
      "drush_batch_process_finished": true                      
  }       
```

**Pull request merged**
