### PR TITLE
Feature: Address restriction

### LINKED ISSUE #45: Provide a local filter for LGD address lookup in Drupal forms
**As a content designer** building Drupal forms containing the LGD address module
**I need to** be able to restrict the returned results on a street lookup to a local area
**So that** information isn't omitted where there are numerous streets of the same name across the country

Currently the address lookup module returns results from the whole country when using the street name as the criteria. The results are limited to 100 addresses, so it often doesn't return information for the related area (Croydon in this instance).

Although the postcode will return the correct area, in some instances, this might not be known; for example, if it's for reporting a pothole.

Having an option to restrict to a particular area would resolve this.

In this example, entering Sandown Road only returns Portsmouth addresses.

image

### PR DESCRIPTION
**Pull request by Adnan-cds**
Additions:
- A Webform Options config entity that lists [Local custodian codes](https://www.ordnancesurvey.co.uk/documents/product-support/support/addressbase-local-custodian-codes.zip).
- Programmatic addition of the above.
- A local custodian code selector for the Address lookup Webform element.
- Passes on the local custodian code to all relevant Geocoder plugins.

Closes #45

### CODE REVIEW

**Comment by ekes** [comment]
Don't know if this is helpful for your passing to gecoders, but I've got a MR https://www.drupal.org/project/geocoder/issues/3406303 so you can pass a query directly to the geocoder plugin - and hence set additional parameters on the query (often setData() is used for passing custom restrictions etc. that a geocoder supports).

**Comment by Adnan-cds** [comment]
> but I've got a MR https://www.drupal.org/project/geocoder/issues/3406303

Hi Ekes,
Very useful feature.  Thanks for pointing out.  I will surely take a look :)

**Comment by Adnan-cds** [comment]
Ready for review.  Uses the recently added "[additional parameter passing to geocoders](https://www.drupal.org/project/geocoder/issues/3406303)" feature of the geocoder module.

### Test steps
- Add the "LocalGov address lookup" element to a Webform.
- While configuring the "Address lookup" element, select a Local authority: screenshot
- If the address lookup element is using the "Localgov OS Places" geocoder, subsequent address lookups will remain limited to the selected local authority.  All other geocoders should remain unaffected.  "Sandown" is a good test candidate street name.

Resolves #45

**Comment by ekes** [comment]
Are the custodian codes going to be useful for https://github.com/localgovdrupal/localgov_os_places_geocoder_provider to be used in other geocoding?

**Comment by Adnan-cds** [comment]
> Are the custodian codes going to be useful for

I think so.  The latest code change in the [OS Places geocoder](https://github.com/localgovdrupal/localgov_os_places_geocoder_provider) added support for the Local custodian code.

**Comment by finnlewis** [comment]
So what's the plan here @Adnan-cds ? Move some config to other localgov modules or keep it here?

**Comment by Adnan-cds** [comment]
> So what's the plan here?

Let's see what Ekes thinks.  We can move the Local custodian code configuration to localgov_geo.  But then it would become site-wide rather than specific to a form element.

**Comment by andybroomfield** [comment]
Form builders will still need to set this in the form as sometimes we want an address for Brighton & Hove only and sometimes we want a UK wide address.

**Comment by finnlewis** [comment]
Discussion in Merge Tuesday: 

 - Ekes: was just thinking of moving the custodian codes table to a more generic place. Could we have a call back?
 - Ekes But no objections to merging this and creating a new issue / merge request to change the source of custodian codes.

**Review by finnlewis — APPROVED** [review]
Sounds like there are no objections to merging this now and addressing the custodian codes move in another issue.

**Comment by Adnan-cds** [comment]
Thanks.  I have just raised a [ticket](https://github.com/localgovdrupal/localgov_forms/issues/68) to explore the use of a callback to source the custodian codes.

**Pull request merged**
