### PR TITLE
Date validation

### LINKED ISSUE #13: Invalid date part value is reset to '0'
If a date part fails validation the data inputed is changed to 0. In my opinion this is not desirable.

When using the LocalGov Forms Date, what I've found is that if client-side validation is disabled on a webform and a user enters text into any of the date parts, when the form is submitted and passes through the various date validation methods, the value entered is changed into a '0'. 

When stepping through the code I found that this setting to '0' was happening on line 250 of the [Datelist.php](https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/lib/Drupal/Core/Datetime/Element/Datelist.php#L250) class in core. The reason I disabled client-side validation was because it was recommended to do so for the GDS date pattern. 

What we would like to happen is for the value **NOT** to be changed into a '0', but to remain as the value that was originally input e.g 'xx'.  We feel that this would provide a better user experience, and that a user should be able to correct what was entered in the date part.

Our objective is to find a way in which we can keep the erroneous value in situ. Below are screenshots showing what is currently happening. Please share your thoughts on this issue. 

**Before validation**
Screenshot 2021-11-30 at 14 15 20

**After Validation**
Screenshot 2021-11-30 at 14 15 33

### PR DESCRIPTION
**Pull request by Adnan-cds**
Nonnumeric date parts are turning into *numeric* values alongside form validation error messages.  Fixed now.

Example: User enters "1A" as a month value.  This fails validation, but then appears as "1" in the month input field alongside the validation failure message.

Resolves #13 

## Test failure
This is down to recent changes to the paragraphs module breaking our [localgov_paragraphs](https://github.com/localgovdrupal/localgov_paragraphs/pull/43) and [localgov_subsites](https://github.com/localgovdrupal/localgov_subsites/pull/75) tests.  The tests for this module run on their own are expected to pass.

### CODE REVIEW

**Review by MattOz-CDS — APPROVED** [review]

**Comment by Adnan-cds** [comment]
Tests are passing.  Ready for review once again.

**Comment by finnlewis** [comment]
Hoping that @ekes might have time to review and comment or approve this week.

It looks good to me on first glance and tests all pass now.

**Comment by finnlewis** [comment]
Just a quick note, @ekes has not had time to look at this. 

@Adnan-cds let us know if this becomes urgent and we'll try to find some time.

**Comment by Adnan-cds** [comment]
>  @ekes has not had time to look at this.

Hi Finn,
Sorry, missed the meeting today.  As far as I remember, Ekes actually said in one of the earlier meetings that he is okay with the approach given that the related date error logged in Drupal's log is coming from Core code.  So this may be ready.  Copying @ekes

**Review by finnlewis — APPROVED** [review]
Just discussing this in merge Monday. Happy for this to be merged if it works, but we've not looked that closely.

**Comment by Adnan-cds** [comment]
Thanks Finn.

**Pull request merged**
