### PR TITLE
1.0.0-beta2 release

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
@Adnan-cds @stephen-cox OK to tag a release?

**Comment by Adnan-cds** [comment]
Hi Finn,
I think it is best not to do a stable release until #34 is resolved.  I am hoping to fix #34 next week.  So perhaps wait for another two weeks before doing the release?

**Comment by finnlewis** [comment]
Hi @Adnan-cds 

This is not meant to be a stable release, but a beta2 bump to support Drupal 10, needed for localgov_microsites 3.x

So still beta, just a fair few updates since December 2022.

1.0.0-beta2

**Review by Adnan-cds — APPROVED** [review]
Thanks.

**Comment by willguv** [comment]
Hi @Adnan-cds how are you getting on with a fix? Thanks!

**Comment by Adnan-cds** [comment]
Hi Will.  I haven't started working on fixing #34.  Hopefully next week.  But this release has gone out already.  Finn explained later that fix for #34 was not essential for this release 1.0.0-beta2.

**Pull request merged**
