### PR TITLE
Replace bhcc geocoders with mock geocoder

### PR DESCRIPTION
**Pull request by Adnan-cds**
Removing the bhcc_central_hub module which we were using for automated and manual testing.  The new [mock geocoder plugin](https://github.com/localgovdrupal/localgov_forms/blob/feature/mock-geocoder/tests/modules/localgov_forms_test/src/Geocoder/Provider/LocalgovMockGeocoder.php) replaces the bhcc_centra_hub_commercial geocoder plugin during automated testing.

Manual testing will become slightly harder in the absence of the bhcc_central_hub module.  The *Nominatim* Geocoder plugin can provide some addresses than can be used instead although it does not act as a total replacement.

### CODE REVIEW

**Review by ekes — APPROVED** [review]

**Review by stephen-cox — APPROVED** [review]
Looks fine to me. Makes sense to have a mock Geocoder provider for testing purposes.

**Comment by Adnan-cds** [comment]
Thanks for the approval.  Merging...

**Comment by andybroomfield** [comment]
@Adnan-cds I'll split out the work you did on the BHCC geocoder and put it somewhere as I want to preserve that.

**Comment by Adnan-cds** [comment]
Thanks Andy.  Yes, that would be great.  The BHCC Geocoder is very useful for manual testing.

**Pull request merged**
