### PR TITLE
Fixes date field validation message presents in reverse order

### PR DESCRIPTION
**Pull request by MattOz-CDS**
Overrides the validateDate method in the Datebase class so that date validation error messages display a UK style date format e.g dd-mm-yyyy.
[https://github.com/localgovdrupal/localgov_forms/issues/67](https://github.com/localgovdrupal/localgov_forms/pull/url)

### CODE REVIEW

**Comment by finnlewis** [comment]
Just discussing in Merge Tuesday with @MattOz-CDS @Adnan-cds @ekes 

Thinking it would be safer to namespace the date format to something like: 

`localgov_forms_uk_html_datetime`

This would keep it namespaced and reduce the chances of conflicts with existing date formats.

**Comment by andybroomfield** [comment]
Is `html_date` an actual [specified date format](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#examples)?

So maybe not calling it html date as thats for the spec.
It would be nice if this was configurable for form builder (not essential for this PR though).

**Comment by MattOz-CDS** [comment]
> Is `html_date` an actual [specified date format](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#examples)?
> 
> So maybe not calling it html date as thats for the spec. It would be nice if this was configurable for form builder (not essential for this PR though).

Alright Andy, thanks for sharing your thoughts on this. The name choice was inspired by the names of other date formats that are present in our Drupal install.  I assumed that this was an established naming convention, so that's why I went with it. I'm happy to change it, that's no problem. What would you recommend? I also agree that it should be configurable for site builders. I'm happy to do that as well, its just that I was looking for a quick win because this change is urgently needed.

**Comment by andybroomfield** [comment]
I don't know, it was a question! :-)
`localgov_forms_date_datetime` is good.

**Pull request merged**
